# Generated by Django 4.0.5 on 2022-08-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscribtion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(max_length=250, null=True, upload_to='images/')),
                ('post_title', models.CharField(max_length=10000)),
                ('post_content', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
